package Vista;

import Indentidad.Usuario;
import static Vista.Principal.listausuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class VisualizarUsuarios extends javax.swing.JInternalFrame {

    public VisualizarUsuarios() {
        initComponents();
        mostrarUsuarioTabla(); //funcion para mostrar los datos de usuario en la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("LISTA DE USUARIOS");

        TablaUsuarios.setBackground(new java.awt.Color(0, 204, 204));
        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void mostrarUsuarioTabla() {
        
        DefaultTableModel modelo;
        String[] colum = {"Nombre", "Id", "Dirección", "Correo", "Celular", "Calificación"};
        String[][] mat = new String[listausuario.size()][6];

        //llenando a la matriz para muestrar el la tabla
        for (int i = 0; i < listausuario.size(); i++) {
            Usuario user = listausuario.get(i);
            mat[i][0] = user.getNombre();
            mat[i][1] = String.valueOf(user.getIdusuario());
            mat[i][2] = user.getDireccion();
            mat[i][3] = user.getCorreo();
            mat[i][4] = Integer.toString(user.getCelular());
            mat[i][5] = user.getCalificacion();

        }
        modelo = new DefaultTableModel(mat, colum);
        TablaUsuarios.setModel(modelo);
    }
}
