
package Vista;

import Indentidad.Bicicleta;
import static Vista.Principal.listabicicleta;
import javax.swing.table.DefaultTableModel;

public class VisualizarBicicleta extends javax.swing.JInternalFrame {

    public VisualizarBicicleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMuestrarPorEstado = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaBicicleta = new javax.swing.JTable();
        btVerBici = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("VISUALIZAR BICICLETA");

        cbMuestrarPorEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMuestrarPorEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Reparación", "Dañada" }));
        cbMuestrarPorEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMuestrarPorEstadoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Seleccione el estado : ");

        tablaBicicleta.setBackground(new java.awt.Color(0, 255, 255));
        tablaBicicleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaBicicleta);

        btVerBici.setText("VIZUALIZAR");
        btVerBici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerBiciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(29, 29, 29)
                .addComponent(cbMuestrarPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btVerBici)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMuestrarPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVerBici, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMuestrarPorEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMuestrarPorEstadoActionPerformed

    }//GEN-LAST:event_cbMuestrarPorEstadoActionPerformed

    private void btVerBiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerBiciActionPerformed

        //int indiceEstado = cbMuestrarPorEstado.getSelectedIndex();
        String est = (String) cbMuestrarPorEstado.getSelectedItem();

        String[] c = {"Chasis", "Marca", "Modelo", "Color","Fech.Mantenimiento", "Estado"};
        DefaultTableModel mode;
        int contadorfila = 0;
        for (int i = 0; i < listabicicleta.size(); i++) {
            Bicicleta bici = listabicicleta.get(i);
            if (est.equals(bici.getEstado())) {
                contadorfila++;
            }
        }

        int a = 0;
        String[][] matrix = new String[contadorfila][6];
        for (int i = 0; i < listabicicleta.size(); i++) {
            Bicicleta bici = listabicicleta.get(i);
            if (est.equals(bici.getEstado())) {
                matrix[a][0] = Integer.toString(bici.getChasis());
                matrix[a][1] = bici.getMarca();
                matrix[a][2] = bici.getModelo();
                matrix[a][3] = bici.getColor();
                matrix[a][4] = String.valueOf(bici.getFechaUltimoMantenimiento());
                matrix[a][5] = bici.getEstado();
                a++;
            }
        }
        mode = new DefaultTableModel(matrix, c);
        tablaBicicleta.setModel(mode);
    }//GEN-LAST:event_btVerBiciActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVerBici;
    private javax.swing.JComboBox<String> cbMuestrarPorEstado;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaBicicleta;
    // End of variables declaration//GEN-END:variables
}
