/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Indentidad.Motos;
import static Vista.Principal.listamotos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class VisualizarMoto extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarMoto
     */
    public VisualizarMoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMuestrarPorEstadoMotos = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaMotos = new javax.swing.JTable();
        btVerMotos = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("VISUALIZAR MOTO");

        cbMuestrarPorEstadoMotos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Reparación", "Dañada" }));
        cbMuestrarPorEstadoMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMuestrarPorEstadoMotosActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setText("Seleccione el estado : ");

        tablaMotos.setBackground(new java.awt.Color(0, 255, 255));
        tablaMotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tablaMotos);

        btVerMotos.setText("VIZUALIZAR");
        btVerMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerMotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(cbMuestrarPorEstadoMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btVerMotos))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMuestrarPorEstadoMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btVerMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMuestrarPorEstadoMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMuestrarPorEstadoMotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMuestrarPorEstadoMotosActionPerformed

    private void btVerMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerMotosActionPerformed

        // Mostramos las motos por estado
        String estadoMoto = String.valueOf(cbMuestrarPorEstadoMotos.getSelectedItem());

        int countEstado = 0;
        for (int i = 0; i < listamotos.size(); i++) {
            Motos moto = listamotos.get(i);
            if (estadoMoto.equals(moto.getEstado())) {
                countEstado++; // contamos los estados
            }
        }

        DefaultTableModel dfm;
        String[] columna = {"Placa", "Modelo", "Marca","Color","Fecha Mantenimiento", "Estado"};
        String[][] matrix = new String[countEstado][6];
        int index = 0;
        for (int i = 0; i < listamotos.size(); i++) {
            Motos moto = listamotos.get(i);
            if (estadoMoto.equals(moto.getEstado())) {
                matrix[index][0] = moto.getPlaca();
                matrix[index][1] = moto.getModelo();
                matrix[index][2] = moto.getMarca();
                matrix[index][3] = moto.getColor();
                matrix[index][4] = String.valueOf(moto.getFechaUltimoMantenimiento());
                matrix[index][5] = moto.getEstado();
                index++;
            }
        }
        dfm = new DefaultTableModel(matrix, columna);
        tablaMotos.setModel(dfm);

    }//GEN-LAST:event_btVerMotosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVerMotos;
    private javax.swing.JComboBox<String> cbMuestrarPorEstadoMotos;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tablaMotos;
    // End of variables declaration//GEN-END:variables
}
