
package Vista;

import Indentidad.Autos;
import static Vista.Principal.listaautos;
import javax.swing.table.DefaultTableModel;

public class VisualizarAuto extends javax.swing.JInternalFrame {

    public VisualizarAuto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMuestrarPorEstadoAutos = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaAutos = new javax.swing.JTable();
        btVerAutos = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("VISUALIZAR AUTOS");

        cbMuestrarPorEstadoAutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Reparación", "Dañada" }));
        cbMuestrarPorEstadoAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMuestrarPorEstadoAutosActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setText("Seleccione el estado : ");

        tablaAutos.setBackground(new java.awt.Color(0, 255, 255));
        tablaAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablaAutos);

        btVerAutos.setText("VIZUALIZAR");
        btVerAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerAutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel41)
                .addGap(29, 29, 29)
                .addComponent(cbMuestrarPorEstadoAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btVerAutos)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMuestrarPorEstadoAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVerAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMuestrarPorEstadoAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMuestrarPorEstadoAutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMuestrarPorEstadoAutosActionPerformed

    private void btVerAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerAutosActionPerformed

        // Aqui mostramos los Autos de acuerdo a su estado
        // Tenemos tres estados DISPONIBLE, REPARACION,DAÑADO
        String estadoAuto = (String) cbMuestrarPorEstadoAutos.getSelectedItem();

        DefaultTableModel dtm;
        // Nombre de las columnas
        String[] columna = {"Placa", "Marca", "Modelo", "Color", "Fecha Mantenimiento", "Estado"};

        int countFilasEstado = 0;
        for (int i = 0; i < listaautos.size(); i++) {
            Autos auto = listaautos.get(i);
            if (estadoAuto.equals(auto.getEstado())) {
                countFilasEstado++;
            }
        }
        // Matriz para mostrar en la tabla los datos de Autos
        String[][] matrix = new String[countFilasEstado][6];

        int indiceFila = 0;
        for (int i = 0; i < listaautos.size(); i++) {
            Autos auto = listaautos.get(i);
            if (estadoAuto.equals(auto.getEstado())) { // Los autos con estado disponible
                matrix[indiceFila][0] = auto.getPlaca();
                matrix[indiceFila][1] = auto.getMarca();
                matrix[indiceFila][2] = auto.getModelo();
                matrix[indiceFila][3] = auto.getColor();
                matrix[indiceFila][4] = String.valueOf(auto.getFechaUltimoMantenimiento()); // Convertimos a string
                matrix[indiceFila][5] = auto.getEstado();
                indiceFila++;
            }
        }
        dtm = new DefaultTableModel(matrix, columna);
        tablaAutos.setModel(dtm); // Mostramos la matriz de autos en la tabla
    }//GEN-LAST:event_btVerAutosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVerAutos;
    private javax.swing.JComboBox<String> cbMuestrarPorEstadoAutos;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tablaAutos;
    // End of variables declaration//GEN-END:variables
}
